/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as OgRouteImport } from './routes/og'
import { Route as PaidRouteImport } from './routes/paid'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TodayRouteImport } from './routes/today'
import { Route as DuelIndexRouteImport } from './routes/duel.index'
import { Route as LIdRouteImport } from './routes/l.$id'
import { Route as OgIndexRouteImport } from './routes/og.index'
import { Route as OgBoardRouteImport } from './routes/og.board'
import { Route as OgDuelRouteImport } from './routes/og.duel'
import { Route as OgListingRouteImport } from './routes/og.listing'
import { Route as OgTextRouteImport } from './routes/og.text'
import { Route as OutIdRouteImport } from './routes/out.$id'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as DLeftRightRouteImport } from './routes/d.$left.$right'
import { Route as DuelLeftRightRouteImport } from './routes/duel.$left.$right'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const OgRoute = OgRouteImport.update({
  id: '/og',
  path: '/og',
  getParentRoute: () => rootRouteImport,
} as any)
const PaidRoute = PaidRouteImport.update({
  id: '/paid',
  path: '/paid',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelIndexRoute = DuelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DuelRoute,
} as any)
const LIdRoute = LIdRouteImport.update({
  id: '/l/$id',
  path: '/l/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OgIndexRoute = OgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OgRoute,
} as any)
const OgBoardRoute = OgBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => OgRoute,
} as any)
const OgDuelRoute = OgDuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => OgRoute,
} as any)
const OgListingRoute = OgListingRouteImport.update({
  id: '/listing',
  path: '/listing',
  getParentRoute: () => OgRoute,
} as any)
const OgTextRoute = OgTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => OgRoute,
} as any)
const OutIdRoute = OutIdRouteImport.update({
  id: '/out/$id',
  path: '/out/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const DLeftRightRoute = DLeftRightRouteImport.update({
  id: '/d/$left/$right',
  path: '/d/$left/$right',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelLeftRightRoute = DuelLeftRightRouteImport.update({
  id: '/$left/$right',
  path: '/$left/$right',
  getParentRoute: () => DuelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/duel': typeof DuelRouteWithChildren
  '/og': typeof OgRouteWithChildren
  '/paid': typeof PaidRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/l/$id': typeof LIdRoute
  '/og/board': typeof OgBoardRoute
  '/og/duel': typeof OgDuelRoute
  '/og/listing': typeof OgListingRoute
  '/og/text': typeof OgTextRoute
  '/out/$id': typeof OutIdRoute
  '/duel/': typeof DuelIndexRoute
  '/og/': typeof OgIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/d/$left/$right': typeof DLeftRightRoute
  '/duel/$left/$right': typeof DuelLeftRightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/paid': typeof PaidRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/l/$id': typeof LIdRoute
  '/og/board': typeof OgBoardRoute
  '/og/duel': typeof OgDuelRoute
  '/og/listing': typeof OgListingRoute
  '/og/text': typeof OgTextRoute
  '/out/$id': typeof OutIdRoute
  '/duel': typeof DuelIndexRoute
  '/og': typeof OgIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/d/$left/$right': typeof DLeftRightRoute
  '/duel/$left/$right': typeof DuelLeftRightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/duel': typeof DuelRouteWithChildren
  '/og': typeof OgRouteWithChildren
  '/paid': typeof PaidRoute
  '/rules': typeof RulesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/today': typeof TodayRoute
  '/l/$id': typeof LIdRoute
  '/og/board': typeof OgBoardRoute
  '/og/duel': typeof OgDuelRoute
  '/og/listing': typeof OgListingRoute
  '/og/text': typeof OgTextRoute
  '/out/$id': typeof OutIdRoute
  '/duel/': typeof DuelIndexRoute
  '/og/': typeof OgIndexRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/d/$left/$right': typeof DLeftRightRoute
  '/duel/$left/$right': typeof DuelLeftRightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/duel'
    | '/og'
    | '/paid'
    | '/rules'
    | '/sitemap.xml'
    | '/today'
    | '/l/$id'
    | '/og/board'
    | '/og/duel'
    | '/og/listing'
    | '/og/text'
    | '/out/$id'
    | '/duel/'
    | '/og/'
    | '/api/stripe/webhook'
    | '/d/$left/$right'
    | '/duel/$left/$right'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/paid'
    | '/rules'
    | '/sitemap.xml'
    | '/today'
    | '/l/$id'
    | '/og/board'
    | '/og/duel'
    | '/og/listing'
    | '/og/text'
    | '/out/$id'
    | '/duel'
    | '/og'
    | '/api/stripe/webhook'
    | '/d/$left/$right'
    | '/duel/$left/$right'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/duel'
    | '/og'
    | '/paid'
    | '/rules'
    | '/sitemap.xml'
    | '/today'
    | '/l/$id'
    | '/og/board'
    | '/og/duel'
    | '/og/listing'
    | '/og/text'
    | '/out/$id'
    | '/duel/'
    | '/og/'
    | '/api/stripe/webhook'
    | '/d/$left/$right'
    | '/duel/$left/$right'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DuelRoute: typeof DuelRouteWithChildren
  OgRoute: typeof OgRouteWithChildren
  PaidRoute: typeof PaidRoute
  RulesRoute: typeof RulesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TodayRoute: typeof TodayRoute
  LIdRoute: typeof LIdRoute
  OutIdRoute: typeof OutIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  DLeftRightRoute: typeof DLeftRightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og': {
      id: '/og'
      path: '/og'
      fullPath: '/og'
      preLoaderRoute: typeof OgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paid': {
      id: '/paid'
      path: '/paid'
      fullPath: '/paid'
      preLoaderRoute: typeof PaidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/': {
      id: '/duel/'
      path: '/'
      fullPath: '/duel/'
      preLoaderRoute: typeof DuelIndexRouteImport
      parentRoute: typeof DuelRoute
    }
    '/l/$id': {
      id: '/l/$id'
      path: '/l/$id'
      fullPath: '/l/$id'
      preLoaderRoute: typeof LIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/': {
      id: '/og/'
      path: '/'
      fullPath: '/og/'
      preLoaderRoute: typeof OgIndexRouteImport
      parentRoute: typeof OgRoute
    }
    '/og/board': {
      id: '/og/board'
      path: '/board'
      fullPath: '/og/board'
      preLoaderRoute: typeof OgBoardRouteImport
      parentRoute: typeof OgRoute
    }
    '/og/duel': {
      id: '/og/duel'
      path: '/duel'
      fullPath: '/og/duel'
      preLoaderRoute: typeof OgDuelRouteImport
      parentRoute: typeof OgRoute
    }
    '/og/listing': {
      id: '/og/listing'
      path: '/listing'
      fullPath: '/og/listing'
      preLoaderRoute: typeof OgListingRouteImport
      parentRoute: typeof OgRoute
    }
    '/og/text': {
      id: '/og/text'
      path: '/text'
      fullPath: '/og/text'
      preLoaderRoute: typeof OgTextRouteImport
      parentRoute: typeof OgRoute
    }
    '/out/$id': {
      id: '/out/$id'
      path: '/out/$id'
      fullPath: '/out/$id'
      preLoaderRoute: typeof OutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$left/$right': {
      id: '/d/$left/$right'
      path: '/d/$left/$right'
      fullPath: '/d/$left/$right'
      preLoaderRoute: typeof DLeftRightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel/$left/$right': {
      id: '/duel/$left/$right'
      path: '/$left/$right'
      fullPath: '/duel/$left/$right'
      preLoaderRoute: typeof DuelLeftRightRouteImport
      parentRoute: typeof DuelRoute
    }
  }
}

interface DuelRouteChildren {
  DuelIndexRoute: typeof DuelIndexRoute
  DuelLeftRightRoute: typeof DuelLeftRightRoute
}

const DuelRouteChildren: DuelRouteChildren = {
  DuelIndexRoute: DuelIndexRoute,
  DuelLeftRightRoute: DuelLeftRightRoute,
}

const DuelRouteWithChildren = DuelRoute._addFileChildren(DuelRouteChildren)

interface OgRouteChildren {
  OgBoardRoute: typeof OgBoardRoute
  OgDuelRoute: typeof OgDuelRoute
  OgListingRoute: typeof OgListingRoute
  OgTextRoute: typeof OgTextRoute
  OgIndexRoute: typeof OgIndexRoute
}

const OgRouteChildren: OgRouteChildren = {
  OgBoardRoute: OgBoardRoute,
  OgDuelRoute: OgDuelRoute,
  OgListingRoute: OgListingRoute,
  OgTextRoute: OgTextRoute,
  OgIndexRoute: OgIndexRoute,
}

const OgRouteWithChildren = OgRoute._addFileChildren(OgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DuelRoute: DuelRouteWithChildren,
  OgRoute: OgRouteWithChildren,
  PaidRoute: PaidRoute,
  RulesRoute: RulesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TodayRoute: TodayRoute,
  LIdRoute: LIdRoute,
  OutIdRoute: OutIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  DLeftRightRoute: DLeftRightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
